### PR TITLE
Make optics hierarchy pic more readable

### PR DESCRIPTION
**Pull request by daron666**

### CODE REVIEW

**Comment by Odomontois** [comment]
Can you also add Zipping/Grate optics which is supertype of Equivalent and subtype of Update and Upcast?

**Comment by daron666** [comment]
@Odomontois signature?

**Comment by daron666** [comment]
@Odomontois done. also included diagram's source file.

**Comment by Odomontois** [comment]
Actually arrows are in the the wrong direction.
Zipping is supertype of Equivalent, so arrow should be from Equivalent to Zipping not otherwise.
Same for Update/Upcast with Zipping

**Comment by daron666** [comment]
@Odomontois done

**Pull request merged**
