### PR TITLE
Add reRaise and adaptError methods

### LINKED ISSUE #112: Analogue of `adaptError` from MonadError for Handle
It would be nice to have something like 
```
def adaptError[A](fa: F[A])(pf: PartialFunction[E, E]): F[A]
```
in `Handle` typeclass

### PR DESCRIPTION
**Pull request by daron666**
Closes #112

### CODE REVIEW

**Comment by Odomontois** [comment]
I bet syntax extensions would be useful

**Comment by daron666** [comment]
@Odomontois done

**Comment by daron666** [comment]
> I bet syntax extensions would be useful

Bet? Are you having gambling issues? :)

**Comment by Odomontois** [comment]
And what about the reraise syntax?

**Comment by Odomontois** [comment]
It would be nice to have exact `reRaise` syntax in the `feither` package

**Pull request merged**
