### PR TITLE
Add mode to @masked annotation

### PR DESCRIPTION
**Pull request by REDNBLACK**
1. `MaskMode.Erased` acts like `erased == true`
2. `MaskMode.Full` acts like `erased == false`
3. `MaskMode.ForLength(offset, maxLength)`
starts masking from `offset` until `maxLength` count of symbols were masked. `maxLength == -1` acts like total string length,

### CODE REVIEW

**Comment by Odomontois** [comment]
Cool extension!
I wonder if we can add regex mode too, with the meaning that the first matched group if any should be masked. 
So `ForLength(n)` would become `Regex(".{n}(.*)")` and `ForLength(n, m)` would become `Regex(".{n}(.{1,m}).*)`

**Comment by Odomontois** [comment]
@REDNBLACK Are you interested to continue to work on this?

**Comment by REDNBLACK** [comment]
Yeah

**Comment by Odomontois** [comment]
If it's possible can you look into this issue #59 as wel

**Comment by Odomontois** [comment]
fixed 59

**Pull request merged**
