### PR TITLE
Remove inlining options in build file

### PR DESCRIPTION
**Pull request by Odomontois**

### CODE REVIEW

**Comment by REDNBLACK** [comment]
@Odomontois What is the reason for the change?

**Comment by Odomontois** [comment]
> @Odomontois What is the reason for the change?

Those options break building the library using jdk 11+, also there isn't strong evidence it could provide any help with real world performance.

**Comment by REDNBLACK** [comment]
@Odomontois Add build for JDK11+ before doing this?

**Comment by Odomontois** [comment]
@REDNBLACK do you mean in travis?

**Comment by REDNBLACK** [comment]
@Odomontois Yeah

**Comment by Odomontois** [comment]
@REDNBLACK yeah we may try, although I don't know if it's good to modify travis to state incompatible with master branch

**Comment by REDNBLACK** [comment]
@Odomontois Also AFAIK Scala 2.13 is not officially compatible with JDK version greater than 11

**Comment by REDNBLACK** [comment]
@Odomontois > there isn't strong evidence it could provide any help with real world performance.
 
But there is, for sure, more optimal byte code. Don’t trust words of other people, measure and check for yourself.

**Comment by Odomontois** [comment]
@REDNBLACK Do you have such an evidence?

**Comment by REDNBLACK** [comment]
Let’s remove it for now, i don’t have enough time to write benchmarks and show you javac-decompiled difference.

**Comment by REDNBLACK** [comment]
It’s like “to use or not to use imp” bikeshedding all over again.

https://gvolpe.github.io/blog/context-bound-vs-implicit-evidence/
https://github.com/DarkDimius/imp-bench

**Pull request merged**
